name: Docker Image CI

on:
  push:
    branches: [ main ]
  # Allows manual triggers from actions tab
  workflow_dispatch:

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out the repo
      id: checkout
      uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: jspanchu/vtk-wasm-target
        flavor: |
          latest=true
        tags: |
          type=semver,enable=true,pattern={{raw}},value={{date 'YYYYMMDD'}}  
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Log in to Docker Hub
      id: login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: jspanchu/vtk-wasm-target:test

    - name: Test # Need to extend this.
      id: test
      run: |
        docker run --rm jspanchu/vtk-wasm-target:test

    - name: Push docker image
      id: push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
