name: Docker Image CI

on:
  push:
    branches: [ main ]
env:
  TEST_TAG: jspanchu/vtk-wasm-target:test
  PUBLISH_TAG: jspanchu/vtk-wasm-target:$(date +%Y%m%d)
  LATEST_TAG: jspanchu/vtk-wasm-target:latest

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out the repo
      id: checkout_repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      id: docker_login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export to Docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}

    - name: Test
      id: test_docker_img
      run: |
        docker run --rm ${{ env.TEST_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.PUBLISH_TAG, env.LATEST_TAG }}
